### ISSUE TITLE
Error during checkout

### ISSUE THREAD

**Issue by meetxtt** [ChristianGabs/btcpay-fossbilling#1]
Hi there.

Thanks for your plugin, looking forward to use BTCPay (server).

After I have installed the plugin to FOSSBilling, and configure it, I get an error during checkout.

`http://btcpayserver/Util/PreciseNumber::parseString():%20Argument%20#1%20($value)%20must%20be%20of%20type%20string,%20null%20given,%20called%20in%20/var/www/website.com/www/library/Payment/Adapter/BTCPay/BTCPay.php%20on%20line%20291`

**Comment by ChristianGabs** [comment]
Looks like your $invoice->base_income is not set, your amount is null on your invoice,

Can you check for me if in database your base_income has amout or is null

I will create an exception anyway and thank for letting me know

**Comment by meetxtt** [comment]
Strange cause I am using BitCart and want to move from BitCart to BTCPay
but my BitCart payment gateway works.

**Comment by ChristianGabs** [comment]
Sorry,

Spot now, base amount is not the right place to look for the full amount, let me do some debug and I will release ASAP a fix for that.

Thank you

**Comment by ChristianGabs** [comment]
Fix on [0.1.4](https://github.com/ChristianGabs/btcpay-fossbilling/releases/tag/0.1.4)

I will do a PR for release this on foss extension

**Comment by ChristianGabs** [comment]
Keeping open, can you download the last version and feedback back ?

Thanks

**Comment by meetxtt** [comment]
Hi.

Thanks for quick fixed, I can confirm that this has been fixed.

But I am not sure (never used BTCPay until now.) if the following error is related to the plugin or BTCPay, I have tried to read about on their documentation but not stumbled on anything that will help me resolve it.

So when product is added to cart, and BTCPay is chosen, -> When I click next I get following error (and FYI some content is masked)

`Error during POST to https://website.com/api/v1/stores/STORE_ID/invoices. Got response (400): {"code":"generic-error","message":"Warning: You have payment methods configured but none of them match any of the requested payment methods or the rate is not available. See logs below:\n06/14/2024 15:27:59:Info Creation of invoice starting\n06/14/2024 15:27:59:Info BTC_EUR: The rating rule is binance(BTC_EUR)\n06/14/2024 15:27:59:Info BTC_EUR: The evaluated rating rule is (62595.73, 62595.74)\n06/14/2024 15:27:59:Info BTC (On-Chain): Payment method details creation took 0 milliseconds\n06/14/2024 15:27:59:Error BTC: Payment method unavailable (Full node not available)\n"}`

If it's not related to the plugin you can close it and mark it solved. :)

btw is it possible that you can send me an email on h4uxir@gmail.com?

**Comment by ChristianGabs** [comment]
Glad to hear,

I will sent you an email

Thanks

**Comment by meetxtt** [comment]
Sorry for re-opening, and I could not try the payment gateway better cause my BTCPay nodes were still syncing.

Currently I am facing error when hitting the checkout button:

PHP Warning:  Object of class BTCPayServer\Util\PreciseNumber could not be converted to int in /var/www/website.com/public_html/vendor/gabordemooij/redbean/RedBeanPHP/QueryWriter/AQueryWriter.php on line 233

**Comment by ChristianGabs** [comment]
Hi,

Is this when you press BTCPay on invoices or return back ?

Thanks

**Comment by meetxtt** [comment]
It's just when I click the Checkout button

![image](https://github.com/ChristianGabs/btcpay-fossbilling/assets/172800650/6364aedc-fa61-4e25-bee7-5b8a4c52d4cf)

Then this error appears.


fös., 14. jún. 2024 kl. 22:17 skrifaði DeVeGabs ***@***.***>:

**Comment by ChristianGabs** [comment]
I do not see the image, can you send that to my email

Thanks

**Comment by meetxtt** [comment]
![image](https://github.com/ChristianGabs/btcpay-fossbilling/assets/172800650/6364aedc-fa61-4e25-bee7-5b8a4c52d4cf)

**Comment by ChristianGabs** [comment]
Please download again [0.1.4](https://github.com/ChristianGabs/btcpay-fossbilling/releases/tag/0.1.4),

Let me know if that will fix the issue

**Comment by meetxtt** [comment]
Solved!

Now it works! Whoop whoop!

**Comment by ChristianGabs** [comment]
Any issue please submit a new Issue

I will keep this gateway as top priority on any issues.

Thanks

**Comment by meetxtt** [comment]
I will submit a new issue, I just felt like it was still the same issue. :)

**Comment by ChristianGabs** [comment]
I do understand, is fine do not worry about it, I do aprecieate you giving feedback so I can improve it as is better when ppl test and play with it as I can't cover alone all aspect.

Thanks again for all your feedback

PS: Look like now you have the last version on FossBilling now as the PR on extension has been migrated to production, so you can use that, I will keep as long as possible 0.1.4 and migrate onto other version when Major Changes are been done.
